### ISSUE TITLE
MDX styles not rendering

### ISSUE THREAD

**Issue by MaggieAppleton** [eggheadio/illustrated-dev#16]
The CSS styles declared in the react components in components/mdx aren't rendering to the site 😢 

Eg. if I change the prism theme, the rendered MDX is still the default vanilla style.
Ditto if I change any CSS on the rest of the components it does't change any MDX styling.

<img width="995" alt="Screenshot 2019-03-30 at 13 53 57" src="https://user-images.githubusercontent.com/5599295/55277042-91504c00-52f3-11e9-9abe-d71264593543.png">

![Screenshot 2019-03-30 at 13 55 41](https://user-images.githubusercontent.com/5599295/55277047-9c0ae100-52f3-11e9-9373-9e1eb3238cab.png)

Don't know enough about the architecture at the moment to solve it.
Would love to know how!

**Comment by vojtaholik** [comment]
https://github.com/eggheadio/illustrated-dev/commit/9efdfc676d9f181b2c39ebaf72063cff6935d330#diff-9d0b060e67d414710ddb48d34d2d33c2R17 fixes this by passing mdx components to `mdxRenderer`.
