### ISSUE TITLE
Responsive mobile version all kinds of broken

### ISSUE THREAD

**Issue by MaggieAppleton** [eggheadio/illustrated-dev#17]
Browsing on phones has a bunch of issues with image scaling, spacing, and layout:

![Screen Recording 2019-04-04 at 07 52 am](https://user-images.githubusercontent.com/5599295/55535350-e226c280-56ae-11e9-8fb1-3c6a1820b037.gif)

I'm not sure of the best way to fix these / best practices for mobile sites. @vojtaholik or @DrShpongle would love your help on this one.

**Comment by MaggieAppleton** [comment]
More terribly sad responsive issues 😅😅
Homepage link is above the button.
And previous post text all collapses into a single column

![Screen Recording 2019-04-04 at 11 49 am](https://user-images.githubusercontent.com/5599295/55550302-d0094c00-56cf-11e9-9240-9e70e9a7b2c3.gif)

**Comment by vojtaholik** [comment]
https://github.com/eggheadio/illustrated-dev/commit/4da8b2bb2e48719650a7a97c2399222333ab20e2 fixes above issues. please feel free to reopen if I missed something. :)
