### ISSUE TITLE
RSS and feed discovery

### ISSUE THREAD

**Issue by joelhooks** [eggheadio/illustrated-dev#18]
We need to get RSS and feed discovery implemented. 

http://www.rssboard.org/rss-autodiscovery

**Comment by vojtaholik** [comment]
https://github.com/eggheadio/illustrated-dev/commit/372a1d27fe421517df76dcba4a96d3f9606ce2ac adds `gatsby-plugin-feed`, which I believe has `autodiscovery` implemented out the gate (I tested a few readers and they did auto detect it).

<img src="https://cl.ly/13875c76271b/Screen%252520Recording%2525202019-04-05%252520at%25252012.43%252520PM.gif" width="350">

https://illustrated.dev/rss.xml
