### ISSUE TITLE
Update Favicon & Social Media Share Image

### ISSUE THREAD

**Issue by MaggieAppleton** [eggheadio/illustrated-dev#20]
Favicon
16px Max
<img width="293" alt="Screenshot 2019-04-09 at 13 15 47" src="https://user-images.githubusercontent.com/5599295/55799582-a2564580-5ac9-11e9-9318-05ef9fba865f.png">

Social share card
480x250px
<img width="381" alt="Screenshot 2019-04-09 at 13 16 01" src="https://user-images.githubusercontent.com/5599295/55799584-a4200900-5ac9-11e9-8d69-ca531fbfc594.png">

**Comment by JDeLay-JR** [comment]
HI @MaggieAppleton is this issue still open? I'd love to take it!

**Comment by MaggieAppleton** [comment]
OG Images and Content stored here; https://github.com/eggheadio/illustrated-dev/blob/9969e7e6def050dec7d8fecf7f90e877d2a0996f/src/components/seo.js

**Comment by MaggieAppleton** [comment]
Updated favicon and OG images

![image](https://user-images.githubusercontent.com/5599295/71465565-e81c8080-27b4-11ea-8a39-a7ca515457a9.png)
