### ISSUE TITLE
Add Egghead Course Cards into Footers

### ISSUE THREAD

**Issue by MaggieAppleton** [eggheadio/illustrated-dev#26]
On the sketchnote pages want to have a card that matches the course cards on the egghead site.

Current illo.dev footer section:
![image](https://user-images.githubusercontent.com/5599295/61051856-18fc2b00-a3b8-11e9-8c72-bdcd247aa402.png)

Egghead course cards:
![image](https://user-images.githubusercontent.com/5599295/61051887-29140a80-a3b8-11e9-8e32-c241fcf616cc.png)

**Comment by MaggieAppleton** [comment]
Copypasta card code from the main egghead site:

```
import React from 'react'
import PropTypes from 'prop-types'
import {css} from 'emotion'

const containerClasses = `bg-white flex flex-grow-1 justify-between flex-column black-90 br2`

class Card extends React.Component {
  static propTypes = {
    overflow: PropTypes.bool,
  }

  static defaultProps = {
    overflow: false,
  }

  render() {
    const containerStyle = {width: '280px'}
    const {overflow, children, className} = this.props
    return (
      <div
        className={`
          eh-shadow-1
          ${containerClasses}
          ${overflow ? 'overflow-hidden' : ''}
          ${className ? className : ''}
        `}
      >
        {children}
      </div>
    )
  }
}

export default Card
```

**Comment by theianjones** [comment]
We could use @joelhooks course preview to get the images, and have it be a link to that course:

![](https://og-image-egghead-course.now.sh/vr-applications-using-react-360)

Those content cards have a lot of state that is required for them to render, although it would be possible to port it over.

**Comment by MaggieAppleton** [comment]
Solved with open graph images
