### ISSUE TITLE
Build hamburger menu for mobile view

### ISSUE THREAD

**Issue by MaggieAppleton** [eggheadio/illustrated-dev#28]
On mobile the menu disappears entirely and there's no way to access any of the pages.

<a href="https://cl.ly/d0cf61ec0e92" target="_blank"><img src="https://d2ddoduugvun08.cloudfront.net/items/0x0h0q1J3f3N3j292Z3y/Screen%20Recording%202019-07-11%20at%2012.35%20pm.gif" style="display: block;height: auto;width: 100%;"/></a>

Need to build a responsive hamburger menu to fix it

**Comment by theianjones** [comment]
#29 closes this :)
