### ISSUE TITLE
add social share options

### ISSUE THREAD

**Issue by joelhooks** [eggheadio/illustrated-dev#8]
We want to make it easy to share these things!

**Comment by vojtaholik** [comment]
https://github.com/eggheadio/illustrated-dev/commit/35989b6d4c9cc2d0343be42df18ca232975e232d adds Twitter and Pinterest share buttons. @MaggieAppleton we can easily add more, see https://www.npmjs.com/package/react-share

**Comment by MaggieAppleton** [comment]
Just added on an email share button too, but those three options feel like enough for now

**Comment by vojtaholik** [comment]
nice! 👍
